---
- name: Add SSH key for passwordless login (pi)
  authorized_key:
    user: pi
    key: '{{ item }}'
  with_file:
    - '{{ ssh_public_key_path }}'

- name: Change default password
  user:
    name: pi
    password: '{{ user_password }}'
