---
- name: Configure sshd
  template:
    src: ../templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 664

- name: Restart sshd service
  become: yes
  service:
    name: sshd
    state: restarted
