---
- name: Install unattended-upgrades packages
  package:
    name: "{{ item }}"
    state: 'present'
  with_items:
    - unattended-upgrades
    - apt-listchanges
    - bsd-mailx

- name: Configure unattended-upgrades `20auto-upgrades`
  template:
    src: ../templates/20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: Configure unattended-upgrades `50unattended-upgrades`
  template:
    src: ../templates/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644

- name: Configure unattended-upgrades `listchanges.conf`
  template:
    src: ../templates/listchanges.conf.j2
    dest: /etc/apt/listchanges.conf
    owner: root
    group: root
    mode: 0644
