# ansible-playbook playbooks/setup-new-raspi.yml --ask-become-pass --user pi --ask-pass
# - Defaults vars
# - Upgrade system include raspi-config
# - Reboot
# - Unattended upgrades
# - Change pi default password
# - Sshd config
---
- hosts: localhost
  become: true
  vars_prompt:
    - name: 'ssh_public_key_path'
      prompt: 'Where is your SSH public key?'
      default: '~/.ssh/id_rsa.pub'
      private: no
    - name: 'user_password'
      prompt: 'What should the user password be?'
      private: yes
      encrypt: 'sha512_crypt'
      confirm: yes
      salt: 'raspberry'
    - name: 'raspi_hostname'
      prompt: 'What your raspi hostname?'
      default: 'rpi'
      private: no
    - name: 'raspi_locale'
      prompt: 'What your raspi locale?'
      default: 'en_US.UTF-8'
      private: no
    - name: 'raspi_timezone'
      prompt: 'What your raspi timezone?'
      default: 'UTC'
      private: no
    - name: 'xkblayout'
      prompt: 'What your raspi xkblayout?'
      default: 'us'
      private: no
    - name: 'wifi_ssid'
      prompt: 'What your wifi ssid?'
      private: no
    - name: 'xkblayout'
      prompt: 'What your wifi password?'
      private: no
    - name: 'xkblayout'
      prompt: 'What your wifi country?'
      private: no

  tasks:
    - include_vars:  ../vars/defaults.yml
    - include_tasks: ../tasks/enable-ssh.yml
    - include_tasks: ../tasks/upgrade-system.yml
    - include_tasks: ../tasks/reboot.yml
    - include_tasks: ../tasks/unattended-upgrades.yml
    - include_tasks: ../tasks/change-default-password.yml
    - include_tasks: ../tasks/sshd.yml
    - include_tasks: ../tasks/hostname.yml
    - include_tasks: ../tasks/locale.yml
    - include_tasks: ../tasks/timezone.yml
    - include_tasks: ../tasks/xkblaybout.yml
    - include_tasks: ../tasks/wifi.yml

