# ansible-playbook playbooks/setup-new-raspi.yml --ask-become-pass --user pi --ask-pass
# - Defaults vars
# - Upgrade system include raspi-config
# - Reboot
# - Unattended upgrades
---
- hosts: localhost
  become: true
  tasks:
    - include_vars: ../vars/defaults.yml
    - include_tasks: ../tasks/upgrade-system.yml
    - include_tasks: ../tasks/reboot.yml
    - include_tasks: ../tasks/unattended-upgrades.yml
